### PR TITLE
Add more tools

### PR DESCRIPTION
**Pull request by nikita36078**

### CODE REVIEW

**Comment by minexew** [comment]
Thanks for these! Could you please clarify the origin of _fishlabs_converter.zip_?

**Comment by nikita36078** [comment]
It's from here: https://4pda.ru/forum/index.php?showtopic=117630&view=findpost&p=54112706

**Comment by minexew** [comment]
Ok -- since it is not an official tool, I would avoid including it in the repo as a binary. Anyways, _/tools/fishlabs_obfuscation.py_ already implements the algorithm, which works both ways.

The other files are definitely fit for inclusion, though.

**Comment by minexew** [comment]
Thanks!

**Pull request merged**
